### PR TITLE
remove forms from redux

### LINKED ISSUE #44: Should we remove form states from the store?
https://github.com/hooligram/hooligram-client/blob/5c37cca2419791c9d698b995f192e4b2e70b6112/app/state/actions/forms.js#L1-L41

Reasoning:
- Same reasoning for why it's a good idea to separate navigation from the store
- I don't see any benefit of putting it there
- Form states should be local to the component
- It will simplify the shape of the store

### PR DESCRIPTION
**Pull request by cglotr**
Fixes #44. 

- Remove form states from redux
- Reduced store shape to:
   ```
   store = {
     countryCode,
     phoneNumber,
     userName,
     verificationCode,
  }
  ```

There are many more things to do actually but I don't want to make too many changes before meeting sync up. I will list things that I think we should discuss:

- Action type naming
- How to structure actions & reducer
- Should the app know about the existence of middlewares?
- Persistence. I think we can just persist on every action trigger since the store is quite small. We can also throttle/debounce the persist rate if performance is an issue
- The app interaction with the backend websocket
- How we handle loading. I am thinking of a middleware-based since promise-based is not possible in our case (due to websocket)

Note:
- Failing tests (will be fixed after the design is confirmed)

### CODE REVIEW

**Comment by cglotr** [comment]
@imranariffin it's still WIP but early feedback would be helpful. When working on this, I realized that the store shape should only be (at least for the MVP):

```
store = {
  countryCode,
  messages: [{...}...],
  phoneNumber,
  userName,
  verificationCode,
}
```

Do you agree with the above shape? Or is there anything missing?

**Comment by imranariffin** [comment]
I'll have a look tonight

**Comment by cglotr** [comment]
- App FSM derived from screens states
- Remove action types prefix so that the app doesn't know about the existence of middlewares
- _Should the app know about the existence of middlewares?_
  - No

**Comment by cglotr** [comment]
Merging to favor fast development & since the app is fully functional.

**Pull request merged**
