### PR TITLE
refactor/imran/clearer-action-types-naming

### PR DESCRIPTION
**Pull request by imranariffin**
#31 

1. rename `INIT` to `APP:STARTUP` so it becomes more obvious
2. differentiate between `WEBSOCKET` actions and `API` actions
3. dispatch `persistence` & `api` actions in correct order

While working on #18 I feel like I had to do some refactorings before able to finish nicely.

### CODE REVIEW

**Comment by imranariffin** [comment]
Before commit 3aabf03:

before-dispatch-wrong-order

**Comment by imranariffin** [comment]
After commit 3aabf03 (note the ordering of the actions):

after-dispatch-correct-order

**Comment by imranariffin** [comment]
> Not tested but the improvement in the screenshot looks nice.

Yeah, from this PR I started to better understand order of action dispatch in redux middleware @cglotr

**Comment by cglotr** [comment]
> > Not tested but the improvement in the screenshot looks nice.
> 
> Yeah, from this PR I started to better understand the order of action dispatch in redux middleware @cglotr

Gonna add this to the weekly agenda. I am pretty interested in Redux middleware too.

**Comment by imranariffin** [comment]
Nice

**Pull request merged**
